# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the rank probability score for a tournament
#'
#' @description Fill down missing values with the latest non-missing value
#' @param m A prediction matrix 
#' @param outcome A prediction matrix 
#' @param rankweights A prediction matrix 
#' @return A vector or list with the NA's replaced by the last observed value.
#' @author Claus Ekstrom <ekstrom@@sund.ku.dk>
#' @examples
#'
#'
#' @export
rps <- function(m, outcome, rankweights = 1L) {
    .Call(`_socceR_rps`, m, outcome, rankweights)
}

